### ISSUE TITLE
Django stack trace after layer rating

### ISSUE THREAD

**Issue by goudine** [MapStory/mapstory#1206]
Selecting a star rating for a layer causes a stack trace in the Django container.
Layer rating still persists.
 
<img width="178" alt="rate_layer" src="https://user-images.githubusercontent.com/17364268/35361657-fe91a460-0116-11e8-84a9-f8ac34c6c885.png">

**Request headers**
Request URL:https://docker/ratings/57/37/rate/
Request Method:POST
Status Code:500 INTERNAL SERVER ERROR
Remote Address:127.0.0.1:443
Referrer Policy:no-referrer-when-downgrade

**Stack trace**
Internal Server Error: /ratings/57/37/rate/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/agon_ratings/views.py", line 84, in rate
    return HttpResponse(json.dumps(data), mimetype="application/json")
  File "/usr/local/lib/python2.7/site-packages/django/http/response.py", line 340, in __init__
    super(HttpResponse, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mimetype'
ERROR:django.request:Internal Server Error: /ratings/57/37/rate/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/agon_ratings/views.py", line 84, in rate
    return HttpResponse(json.dumps(data), mimetype="application/json")
  File "/usr/local/lib/python2.7/site-packages/django/http/response.py", line 340, in __init__
    super(HttpResponse, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mimetype'

**Comment by jonpmarino** [comment]
closing. not current on lab.mapstory.org as of july 23
