### ISSUE TITLE
Remove dead API code for uploading thumbnails

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#1303]
#1247 removes the front end code.

**Comment by cuttlefish** [comment]
PR at #1326

**Comment by cuttlefish** [comment]
Remove test causing:
```======================================================================
ERROR: test_upload_gif_thumbnail (mapstory.apps.thumbnails.tests.TestThumbnailImage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/mapstory/mapstory/apps/thumbnails/tests.py", line 45, in test_upload_gif_thumbnail
    save=True
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 111, in save
    self.instance.save()
  File "/srv/mapstory/mapstory/apps/thumbnails/models.py", line 46, in save
    resize_gif(str(self.thumbnail_image.path), None, (thumbnail_width, thumbnail_height))
NameError: global name 'resize_gif' is not defined```

**Comment by goudine** [comment]
Removed failing tests with [PR](https://github.com/MapStory/mapstory/pull/1344)
