### ISSUE TITLE
Users are unable to create layers until they have imported a layer first. production only.

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#366]
Users are unable to use the Create Layer feature if they have not previously imported a layer. We need to fix the create layer feature so that users who have not previously imported a layer can use the feature.

The purpose of the Create Layer feature was to empower users who know a significant amount about a topic, but may not have starter data about it to import. If we prevent users from using Create Layer who haven't done an import yet, we are rendering that feature unusable for the user type that it was designed to empower.

**Comment by Coop56** [comment]
I can't reproduce this on local or on demo.  This is only happening on production.  When it tries to create the datastore it errors out.

Internal Server Error: /layers/create
Traceback (most recent call last):
  File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/srv/git/mapstory/mapstory/mapstory/views.py", line 713, in layer_create
    layers = creator.handle(configuration_options=configuration_options)
  File "/home/mapstory/.virtualenvs/mapstory/src/osgeo-importer/osgeo_importer/importers.py", line 89, in handle
    layers = self.import_file(configuration_options=configuration_options)
  File "/srv/git/mapstory/mapstory/mapstory/importers.py", line 70, in import_file
    store_created = create_geoserver_db_featurestore(store_type='geogig', store_name=feature_type['store']['name'])
  File "/srv/git/mapstory/geonode/geonode/upload/utils.py", line 66, in create_geoserver_db_featurestore
    "Error code (%s) from GeoServer: %s" %
FailedRequestError: Error code (409) from GeoServer: {"response":{"success":false,"error":"Cannot run init on an already initialized repository."}}

**Comment by jonpmarino** [comment]
we will have more intel once docker deployments are complete.

**Comment by jonpmarino** [comment]
closing. this did not occur on prod in the April 4 RFT sessions on an updated prod build.
